name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  releases:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 BUILDPATH=./bin/kubecfg-linux-amd64 make
          GOOS=linux GOARCH=arm BUILDPATH=./bin/kubecfg-linux-arm make
          GOOS=linux GOARCH=arm64 BUILDPATH=./bin/kubecfg-linux-arm64 make
          GOOS=windows GOARCH=amd64 BUILDPATH=./bin/kubecfg-windows-amd64.exe make
          GOOS=darwin GOARCH=amd64 BUILDPATH=./bin/kubecfg-darwin-amd64 make
          GOOS=darwin GOARCH=arm64 BUILDPATH=./bin/kubecfg-darwin-arm64 make

      - uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "./bin/*"

